name: smart_parking_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.2
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_map: ^7.0.2 # Ensure you check for the latest version
  latlong2: ^0.9.1
  google_maps_flutter: ^2.7.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_dash: ^1.0.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.3
  fluttertoast: ^8.2.6
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  the_apple_sign_in: ^1.1.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  location: ^7.0.0
  mocktail: ^0.3.0
  flutter_google_places_hoc081098: ^2.0.0
  flutter_local_notifications: ^17.2.1+2
  firebase_messaging: ^15.0.4
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  geolocator: ^9.0.0
  pdf: ^3.8.1
  printing: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.17
  integration_test:
    sdk: flutter
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
