name: Continuous Integration

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - develop
      - main
  

jobs:
  build_flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter_version: [3.22.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --debug

  lint_flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter_version: [3.22.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Lint
        run: flutter analyze

  test_flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter_version: [3.22.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test
