name: Integration Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - develop

jobs:
  integration_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'  # Specify your Flutter version
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Firebase Emulator
      run: |
        npm install -g firebase-tools
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Run integration tests with Firebase Emulator
      run: |
        firebase emulators:exec --project demo-project --only auth,firestore "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: integration-test-results
        path: integration_test/