name: Integration Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - develop

jobs:
  integration_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Firebase Emulator
      run: |
        npm install -g firebase-tools
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Debug info
      run: |
        echo "Chrome version:"
        google-chrome --version
        echo "Flutter version:"
        flutter --version
        echo "Listing integration test files:"
        ls -l integration_test/

    - name: Run all integration tests
      run: |
        firebase emulators:exec --project demo-project --only auth,firestore "flutter test integration_test"
      env:
        CHROME_EXECUTABLE: /usr/bin/google-chrome

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test-results
        path: integration_test/